### UPDATE
PUT http://localhost:3001/api/calendars/68f13d738bdbb5821b6bfc5f
Content-Type: application/json

{
  "title": "Seguimiento Proyecto (Actualizado)",
  "organizer": "jose.perez",
  "organizerEmail": "jose.perez@example.com",
  "description": "Actualizar estado del proyecto y tareas clave",
  "startDate": "2025-11-10T10:00:00.000Z",
  "endDate": "2025-11-10T11:00:00.000Z",
  "keywords": ["seguimiento", "proyecto"],
  "notificationChannel": "in-app"
}